# =========================================================
# MySQL
# =========================================================
# Creación de la imagen con el SGDB

# carga la imagen indicada en el fichero .env (5.7)
FROM mysql:${mysql_version}
